<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getTechnologies, saveProjectTechnologies, type Technology, type TechnologyCategory } from '../api/technologyApi'
const props = defineProps<{ projectId: string; projectName: string }>(); const emit = defineEmits<{ back: [] }>()
const all = ref<Technology[]>([]); const selected = ref<string[]>([]); const saving = ref(false); const error = ref<string | null>(null)
const categories: { key: TechnologyCategory; label: string }[] = [{ key: 'Frontend', label: 'Frontend' }, { key: 'Backend', label: 'Backend' }, { key: 'Database', label: 'Database' }, { key: 'Infrastructure', label: 'Infrastruktur / DevOps' }, { key: 'Testing', label: 'Testing' }, { key: 'Integration', label: 'API / Integrasjon' }, { key: 'Tooling', label: 'Verktøy' }]
const grouped = computed(() => categories.map(category => ({ ...category, items: all.value.filter(item => item.category === category.key) })).filter(category => category.items.length))
async function load() { try { all.value = await getTechnologies() } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente teknologier.' } }
async function save() { saving.value = true; try { await saveProjectTechnologies(props.projectId, selected.value); emit('back') } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke lagre teknologier.' } finally { saving.value = false } }
onMounted(load)
</script>
<template><main class="technology-page"><header class="technology-header"><button class="back-link" type="button" @click="emit('back')">← Tilbake til prosjekt</button><p class="eyebrow">PROSJEKTINNSTILLINGER</p><h1>Teknologier</h1><p class="muted">Velg teknologistacken for {{ projectName }}.</p></header><p v-if="error" class="error-text">{{ error }}</p><section v-if="grouped.length" class="technology-grid"><article v-for="category in grouped" :key="category.key" class="technology-card"><h2>{{ category.label }}</h2><label class="select-label">Velg teknologier<select v-model="selected" class="technology-select" multiple><option v-for="technology in category.items" :key="technology.id" :value="technology.id">{{ technology.name }}</option></select></label><p class="select-hint">Hold Ctrl eller Cmd for å velge flere.</p></article></section><div v-else-if="!error" class="empty-state"><h2>Ingen teknologier tilgjengelig</h2><p class="muted">Kjør databasen sin migration for å legge inn teknologikatalogen.</p></div><footer class="technology-footer"><span class="muted">{{ selected.length }} teknologier valgt</span><button class="primary-button save-button" type="button" :disabled="saving || !grouped.length" @click="save">{{ saving ? 'Lagrer…' : 'Lagre teknologistack' }}</button></footer></main></template>
<style scoped>.technology-page{min-height:100vh;padding:48px clamp(20px,6vw,88px);color:#f5f7fb;background:#0b1020}.technology-header,.technology-grid,.technology-footer,.empty-state{max-width:1100px;margin:0 auto}.back-link{margin-bottom:34px;padding:0;border:0;color:#b7f36b;background:transparent}.eyebrow{margin:0 0 10px;color:#b7f36b;font-size:.75rem;font-weight:700;letter-spacing:.16em}h1{margin:0 0 10px;font:600 clamp(2rem,4vw,3.4rem)/1 'Space Grotesk',sans-serif;letter-spacing:-.05em}h2{margin:0 0 18px;font:600 1.15rem 'Space Grotesk',sans-serif}.muted{color:#9da9c3}.technology-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin-top:36px}.technology-card{padding:22px;border:1px solid #25304a;border-radius:16px;background:#121a30}.select-label{display:grid;gap:8px;color:#9da9c3;font-size:.85rem}.technology-select{min-height:105px;padding:9px;border:1px solid #34415f;border-radius:9px;color:#f5f7fb;background:#10182d}.technology-select:focus{border-color:#b7f36b;outline:none}.technology-select option{padding:8px}.select-hint{margin:10px 0 0;color:#7785a2;font-size:.75rem}.technology-footer{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:24px}.save-button{width:auto}.error-text{color:#ffb8c2}.empty-state{margin-top:36px;padding:45px 20px;border:1px dashed #34415f;border-radius:16px;text-align:center}@media(max-width:600px){.technology-footer{align-items:stretch;flex-direction:column}.save-button{width:100%}}</style>
