<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getProjectTasks, updateTaskStatus, type ProjectTask } from '../api/taskApi'
const props = defineProps<{ projectId: string; projectName: string }>(); const emit = defineEmits<{ back: [] }>(); const tasks = ref<ProjectTask[]>([]); const loading = ref(true); const error = ref<string | null>(null); const dragging = ref<ProjectTask | null>(null)
const columns = [{ key: 'Backlog', title: 'Backlog' }, { key: 'Todo', title: 'Todo' }, { key: 'InProgress', title: 'Pågår' }, { key: 'InReview', title: 'Til gjennomgang' }, { key: 'Done', title: 'Ferdig' }]
async function load() { try { tasks.value = await getProjectTasks(props.projectId) } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente oppgaver.' } finally { loading.value = false } }
function items(status: string) { return tasks.value.filter(task => task.status === status) }
function startDrag(task: ProjectTask) { dragging.value = task }
async function drop(status: string) { if (!dragging.value || dragging.value.status === status) return; const task = dragging.value; const previous = task.status; task.status = status; dragging.value = null; try { await updateTaskStatus(props.projectId, task.id, status) } catch (e) { task.status = previous; error.value = e instanceof Error ? e.message : 'Kunne ikke flytte oppgaven.' } }
onMounted(load)
</script>
<template><main class="kanban-page"><header class="kanban-header"><div><button class="back-link" type="button" @click="emit('back')">← Tilbake til prosjekt</button><p class="eyebrow">{{ projectName }}</p><h1>Kanban</h1><p class="muted">Dra oppgaver mellom kolonnene for å oppdatere status.</p></div></header><p v-if="error" class="error-text">{{ error }}</p><p v-if="loading" class="muted">Laster oppgaver…</p><div v-else class="board"><section v-for="column in columns" :key="column.key" class="column" @dragover.prevent @drop="drop(column.key)"><header><h2>{{ column.title }}</h2><span>{{ items(column.key).length }}</span></header><div class="cards"><article v-for="task in items(column.key)" :key="task.id" class="task-card" draggable="true" @dragstart="startDrag(task)"><span class="priority">{{ task.priority }}</span><h3>{{ task.title }}</h3><p v-if="task.description" class="muted">{{ task.description }}</p><small>{{ task.featureTitle || 'Ingen feature' }}</small></article><p v-if="!items(column.key).length" class="empty-column">Slipp oppgaver her</p></div></section></div></main></template>
<style scoped>.kanban-page{min-height:100vh;padding:48px clamp(20px,5vw,72px);color:#f5f7fb;background:#0b1020}.kanban-header{max-width:1300px;margin:0 auto 28px}.back-link{display:block;margin-bottom:28px;padding:0;border:0;color:#b7f36b;background:transparent}.eyebrow{color:#b7f36b;font-size:.75rem;font-weight:700;letter-spacing:.16em}.muted{color:#9da9c3}.board{display:grid;grid-template-columns:repeat(5,minmax(210px,1fr));gap:14px;max-width:1300px;margin:auto;overflow-x:auto;padding-bottom:18px}.column{min-height:480px;padding:14px;border:1px solid #25304a;border-radius:16px;background:#10182d}.column>header{display:flex;align-items:center;justify-content:space-between;padding-bottom:12px;border-bottom:1px solid #25304a}.column h2{margin:0;font-size:1rem}.column header span{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;color:#0b1020;background:#b7f36b;font-size:.8rem;font-weight:700}.cards{display:grid;gap:10px;margin-top:12px}.task-card{padding:14px;border:1px solid #34415f;border-radius:12px;background:#121a30;cursor:grab}.task-card:active{cursor:grabbing}.task-card h3{margin:10px 0 6px;font-size:.98rem}.task-card small{color:#91a2c4}.priority{float:right;color:#ffcf8a;font-size:.7rem;font-weight:700}.empty-column{padding:28px 8px;border:1px dashed #34415f;border-radius:10px;color:#667694;text-align:center;font-size:.85rem}.error-text{color:#ffb8c2}@media(max-width:1100px){.board{grid-template-columns:repeat(5,220px)}}
</style>
