<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getProjectTasks, type ProjectTask } from '../api/taskApi'
const props = defineProps<{ projectId: string; projectName: string }>(); const emit = defineEmits<{ back: [] }>(); const tasks = ref<ProjectTask[]>([]); const loading = ref(true); const error = ref<string | null>(null)
async function load() { try { tasks.value = await getProjectTasks(props.projectId) } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente oppgaver.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><main class="tasks-page"><header class="tasks-header"><div><button class="back-link" type="button" @click="emit('back')">← Tilbake til prosjekt</button><p class="eyebrow">{{ projectName }}</p><h1>Oppgaver</h1><p class="muted">Alle oppgaver i prosjektet, samlet på ett sted.</p></div></header><p v-if="loading" class="muted">Laster oppgaver…</p><p v-if="error" class="error-text">{{ error }}</p><div v-else-if="tasks.length" class="task-list"><article v-for="task in tasks" :key="task.id" class="task-card"><div class="task-top"><span class="status-pill">{{ task.status }}</span><span class="priority">{{ task.priority }}</span></div><h2>{{ task.title }}</h2><p v-if="task.description" class="muted">{{ task.description }}</p><p class="feature-label">{{ task.featureTitle || 'Ingen feature' }}</p><span v-if="task.aiSource !== 'Manual'" class="ai-label">AI-generert</span></article></div><div v-else-if="!loading" class="empty-state"><h2>Ingen oppgaver ennå</h2><p class="muted">Godkjenn AI-oppgaver eller opprett en feature for å komme i gang.</p></div></main></template>
<style scoped>.tasks-page{min-height:100vh;padding:48px clamp(20px,6vw,88px);color:#f5f7fb;background:#0b1020}.tasks-header,.task-list,.empty-state{max-width:1100px;margin:0 auto}.back-link{display:block;margin-bottom:30px;padding:0;border:0;color:#b7f36b;background:transparent}.eyebrow{margin:0 0 10px;color:#b7f36b;font-size:.75rem;font-weight:700;letter-spacing:.16em}h1{margin:0 0 10px;font:600 clamp(2rem,4vw,3.4rem)/1 'Space Grotesk',sans-serif}.task-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;margin-top:30px}.task-card{padding:22px;border:1px solid #25304a;border-radius:16px;background:#121a30}.task-top{display:flex;justify-content:space-between;gap:12px}.status-pill,.ai-label{color:#b7f36b;font-size:.75rem;font-weight:700}.priority{color:#ffcf8a;font-size:.75rem;font-weight:700}.task-card h2{margin:14px 0 8px}.muted{color:#9da9c3}.feature-label{margin:18px 0 0;color:#91a2c4;font-size:.85rem}.ai-label{display:inline-block;margin-top:12px}.empty-state{margin-top:30px;padding:60px 20px;border:1px dashed #34415f;text-align:center}.error-text{color:#ffb8c2}</style>
