<script setup lang="ts">
import { onMounted, ref } from 'vue'; import ConfirmDialog from '../../../shared/components/ConfirmDialog.vue'; import { deleteProjectTask, getProjectTask, updateProjectTask, updateTaskStatus } from '../api/taskApi'; import './TaskDetailPage.css'
const props = defineProps<{ projectId: string; taskId: string; projectName: string }>(); const emit = defineEmits<{ back: [] }>(); const task = ref<any>(null); const editing = ref(false); const showDeleteDialog = ref(false); const saving = ref(false); const error = ref<string | null>(null); const form = ref({ title: '', description: '', priority: 'Medium' })
async function load() { try { task.value = await getProjectTask(props.projectId, props.taskId); form.value = { title: task.value.title, description: task.value.description ?? '', priority: task.value.priority } } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente oppgaven.' } }
async function save() { saving.value = true; try { await updateProjectTask(props.projectId, props.taskId, form.value); editing.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke lagre oppgaven.' } finally { saving.value = false } }
async function changeStatus() { try { await updateTaskStatus(props.projectId, props.taskId, task.value.status); await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke oppdatere status.' } }
async function remove() { saving.value = true; try { await deleteProjectTask(props.projectId, props.taskId); emit('back') } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke slette oppgaven.' } finally { saving.value = false; showDeleteDialog.value = false } }; onMounted(load)
</script>
<template><main class="detail"><button class="back" type="button" @click="emit('back')">← Tilbake til oppgaver</button><p v-if="error" class="error">{{ error }}</p><template v-if="task"><p class="eyebrow">{{ projectName }}</p><template v-if="editing"><input v-model="form.title" class="input" maxlength="200"/><textarea v-model="form.description" class="input" rows="5"></textarea><select v-model="form.priority" class="input"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><div class="actions"><button class="primary" type="button" :disabled="saving" @click="save">Lagre</button><button type="button" @click="editing = false">Avbryt</button></div></template><template v-else><h1>{{ task.title }}</h1><p class="muted">{{ task.description }}</p><label>Status<select v-model="task.status" @change="changeStatus"><option>Backlog</option><option>Todo</option><option>InProgress</option><option>InReview</option><option>Done</option><option>Cancelled</option></select></label><p>Prioritet: {{ task.priority }}</p><div class="actions"><button class="primary" type="button" @click="editing = true">Rediger</button><button class="danger" type="button" @click="showDeleteDialog = true">Slett oppgave</button></div></template><section><h2>Aktivitetslogg</h2><p v-if="!task.activities?.length" class="muted">Ingen aktiviteter ennå.</p><article v-for="activity in task.activities" :key="activity.id"><strong>{{ activity.action }}</strong><p>{{ activity.description }}</p></article></section></template><ConfirmDialog v-if="showDeleteDialog" :open="true" title="Slett oppgave" :message="`Er du sikker på at du vil slette «${task?.title}»? Dette kan ikke angres.`" @cancel="showDeleteDialog = false" @confirm="remove" /></main></template>
<style scoped>.detail{min-height:100vh;padding:48px clamp(20px,8vw,140px);color:#f5f7fb;background:#0b1020}.back{border:0;color:#b7f36b;background:transparent}.eyebrow{color:#b7f36b;font-weight:700;letter-spacing:.14em}.muted{color:#9da9c3}h1{font-size:clamp(2rem,5vw,4rem)}label,.input{display:block;margin-top:18px}select,.input{box-sizing:border-box;width:100%;max-width:600px;padding:12px;color:#fff;background:#121a30;border:1px solid #34415f;border-radius:8px}section{margin-top:40px;padding-top:20px;border-top:1px solid #25304a}article{padding:14px 0;border-bottom:1px solid #25304a}.actions{display:flex;gap:10px;margin-top:22px}.actions button{padding:10px 15px;border:1px solid #34415f;border-radius:8px;color:#fff;background:transparent;cursor:pointer}.actions .primary{color:#0b1020;background:#b7f36b;border-color:#b7f36b}.actions .danger{color:#ffb8c2;border-color:#8b4655}.error{color:#ffb8c2}</style>
