<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { generateFeaturePlan, getAiTaskSuggestions, getFeatures, reviewAiTask, type Feature } from '../api/featureApi'
const props = defineProps<{ projectId: string; projectName: string }>()
const emit = defineEmits<{ back: [] }>()
const features = ref<Feature[]>([]); const loading = ref(true); const error = ref<string | null>(null); const showGenerator = ref(false); const request = ref(''); const category = ref('Backend'); const generating = ref(false); const generatedPlan = ref<string | null>(null)
const tasks = ref<{ id: string; title: string; description?: string; context?: string; approvalStatus: string }[]>([])
const plan = computed(() => { if (!generatedPlan.value) return null; const raw = generatedPlan.value.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim(); try { const a = raw.indexOf('{'); const b = raw.lastIndexOf('}'); const x = JSON.parse(a >= 0 && b > a ? raw.slice(a, b + 1) : raw); return { title: x.title ?? 'AI-forslag', description: x.description ?? '', raw: '' } } catch { return { title: 'AI-forslag', description: '', raw } } })
async function load() { try { features.value = await getFeatures(props.projectId) } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente features.' } finally { loading.value = false } }
async function generate() { if (!request.value.trim()) return; generating.value = true; error.value = null; try { const result = await generateFeaturePlan(props.projectId, request.value.trim(), category.value); generatedPlan.value = result.proposedPlan; tasks.value = await getAiTaskSuggestions(result.id) } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke generere feature-plan.' } finally { generating.value = false } }
async function review(task: typeof tasks.value[number], approved: boolean) { try { await reviewAiTask(task.id, approved); task.approvalStatus = approved ? 'Approved' : 'Rejected' } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke oppdatere oppgaven.' } }
onMounted(load)
</script>
<template><main class="features-page"><header class="features-header"><div><button class="back-link" type="button" @click="emit('back')">← Tilbake til prosjekt</button><p class="eyebrow">{{ projectName }}</p><h1>Features og oppgaver</h1><p class="muted">Planlegg funksjonalitet og bryt den ned i konkrete oppgaver.</p></div><button class="primary-button feature-button" type="button" @click="showGenerator = !showGenerator">{{ showGenerator ? 'Lukk AI' : 'Ny feature med AI' }}</button></header><section v-if="showGenerator" class="generator-card"><p class="eyebrow">AI-PLANLEGGER</p><h2>Velg stack</h2><select v-model="category" class="stack-select"><option>Frontend</option><option>Backend</option><option>Database</option><option>Infrastructure</option><option>Testing</option><option>Integration</option><option>Tooling</option></select><h2>Hva skal featuren gjøre?</h2><textarea v-model="request" rows="4" placeholder="Beskriv featuren..."></textarea><button class="primary-button" type="button" :disabled="generating || !request.trim()" @click="generate">{{ generating ? 'Genererer…' : 'Generer feature og oppgaver' }}</button></section><section v-if="plan" class="suggestion-card"><span class="status-pill">AI-FORSLAG · {{ category }}</span><h2>{{ plan.title }}</h2><p class="muted">{{ plan.description }}</p><div class="suggested-tasks"><article v-for="(task, index) in tasks" :key="task.id" class="suggested-task"><span class="task-number">{{ index + 1 }}</span><div class="task-content"><h3>{{ task.title }}</h3><p v-if="task.description" class="muted">{{ task.description }}</p><small v-if="task.context">{{ task.context }}</small><div v-if="task.approvalStatus === 'PendingApproval'" class="task-actions"><button class="approve-button" type="button" @click="review(task, true)">Godkjenn</button><button class="reject-button" type="button" @click="review(task, false)">Avvis</button></div><span v-else class="reviewed-status">{{ task.approvalStatus === 'Approved' ? 'Godkjent' : 'Avvist' }}</span></div></article></div></section><p v-if="error" class="error-text">{{ error }}</p><p v-if="loading" class="muted">Laster features…</p><div v-else-if="features.length" class="feature-list"><article v-for="feature in features" :key="feature.id" class="feature-card"><span class="status-pill">{{ feature.status }}</span><h2>{{ feature.title }}</h2><p v-if="feature.description" class="muted">{{ feature.description }}</p><p class="task-count">{{ feature.tasks.length }} oppgaver</p></article></div><div v-else class="empty-state"><h2>Ingen features ennå</h2><p class="muted">Velg stack og bruk AI-planleggeren for å lage en feature.</p></div></main></template>
<style scoped>.features-page{min-height:100vh;padding:48px clamp(20px,6vw,88px);color:#f5f7fb;background:#0b1020}.features-header,.feature-list,.empty-state,.generator-card,.suggestion-card{max-width:1100px;margin:0 auto}.features-header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:24px}.back-link{display:block;margin-bottom:30px;padding:0;border:0;color:#b7f36b;background:transparent}.eyebrow{margin:0 0 10px;color:#b7f36b;font-size:.75rem;font-weight:700;letter-spacing:.16em}h1{margin:0 0 10px;font:600 clamp(2rem,4vw,3.4rem)/1 'Space Grotesk',sans-serif}h2{margin:10px 0 7px}h3{margin:0 0 5px}.muted{color:#9da9c3}.generator-card,.suggestion-card{margin-bottom:24px;padding:24px;border:1px solid #34415f;border-radius:18px;background:#121a30}.stack-select,.generator-card textarea{display:block;width:100%;box-sizing:border-box;margin:8px 0 18px;padding:12px;border:1px solid #34415f;border-radius:9px;color:#f5f7fb;background:#10182d}.generator-card textarea{resize:vertical}.suggested-tasks{display:grid;gap:10px;margin-top:22px;padding-top:18px;border-top:1px solid #25304a}.suggested-task{display:flex;gap:14px;padding:14px;border:1px solid #25304a;border-radius:12px;background:#10182d}.task-content{flex:1}.task-number{display:grid;flex:0 0 28px;place-items:center;width:28px;height:28px;border-radius:50%;color:#0b1020;background:#b7f36b;font-weight:700}.suggested-task small{color:#7785a2}.task-actions{display:flex;gap:8px;margin-top:14px}.task-actions button{padding:8px 12px;border:1px solid;border-radius:8px;font-weight:700;cursor:pointer}.approve-button{color:#0b1020;background:#b7f36b;border-color:#b7f36b}.reject-button{color:#ffb8c2;background:transparent;border-color:#8b4655}.reviewed-status,.status-pill{color:#b7f36b;font-weight:700}.reviewed-status{display:inline-block;margin-top:14px}.feature-list{display:grid;gap:16px}.feature-card{padding:24px;border:1px solid #25304a;border-radius:18px;background:#121a30}.task-count{color:#9da9c3}.empty-state{margin-top:30px;padding:60px 20px;border:1px dashed #34415f;text-align:center}.error-text{color:#ffb8c2}@media(max-width:650px){.features-header{align-items:stretch;flex-direction:column}.task-actions{flex-direction:column}.task-actions button{width:100%}}</style>
