global using MediatR;
global using MediatR.RequestHandling;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Server_api.Data;
global using Server_api.Infrastructure.Authentication;
global using Server_api.Infrastructure.Endpoints;
global using Server_api.Models;
