<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { getProjectOverview, saveProjectOverview } from '../api/projectOverviewApi'
const props = defineProps<{ projectId: string; projectName: string }>(); const emit = defineEmits<{ back: [] }>(); const appGoal = ref(''); const targetAudience = ref(''); const productContext = ref(''); const loading = ref(true); const saving = ref(false); const saved = ref(false); const error = ref<string | null>(null)
async function load() { try { const value = await getProjectOverview(props.projectId); appGoal.value = value.appGoal ?? ''; targetAudience.value = value.targetAudience ?? ''; productContext.value = value.productContext ?? '' } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke hente prosjektkontekst.' } finally { loading.value = false } }
async function save() { saving.value = true; saved.value = false; error.value = null; try { await saveProjectOverview(props.projectId, { appGoal: appGoal.value, targetAudience: targetAudience.value, productContext: productContext.value }); saved.value = true } catch (e) { error.value = e instanceof Error ? e.message : 'Kunne ikke lagre prosjektkontekst.' } finally { saving.value = false } }
onMounted(load)
</script>
<template><main class="overview-page"><header><button class="back-link" type="button" @click="emit('back')">← Tilbake til prosjekter</button><p class="eyebrow">PROSJEKTOVERSIKT</p><h1>{{ projectName }}</h1><p class="muted">Beskriv appen slik at AI kan foreslå riktige features og oppgaver.</p></header><section class="overview-card"><p v-if="loading" class="muted">Laster prosjektkontekst…</p><template v-else><label>Hva skal appen gjøre?<textarea v-model="appGoal" rows="6"></textarea></label><label>Hvem er målgruppen?<textarea v-model="targetAudience" rows="3"></textarea></label><label>Produktkontekst og regler<textarea v-model="productContext" rows="5"></textarea></label><button class="primary-button" type="button" :disabled="saving" @click="save">{{ saving ? 'Lagrer…' : 'Lagre prosjektkontekst' }}</button><p v-if="saved" class="saved">✓ Prosjektkontekst lagret</p></template><p v-if="error" class="error-text">{{ error }}</p></section></main></template>
<style scoped>.overview-page{min-height:100vh;padding:48px clamp(20px,6vw,88px);color:#f5f7fb;background:#0b1020}.overview-page header,.overview-card{max-width:760px;margin:0 auto}.back-link{margin-bottom:32px;padding:0;border:0;color:#b7f36b;background:transparent}.eyebrow{color:#b7f36b;font-size:.75rem;font-weight:700;letter-spacing:.16em}h1{margin:0 0 10px;font:600 clamp(2.2rem,5vw,4rem)/1 'Space Grotesk',sans-serif}.muted{color:#9da9c3}.overview-card{display:grid;gap:20px;margin-top:36px;padding:28px;border:1px solid #25304a;border-radius:18px;background:#121a30}label{display:grid;gap:8px;color:#dce3f2;font-weight:600}textarea{width:100%;box-sizing:border-box;padding:12px;border:1px solid #34415f;border-radius:9px;color:#f5f7fb;background:#10182d;resize:vertical}.saved{color:#b7f36b}.error-text{color:#ffb8c2}.primary-button{width:auto}</style>
